/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_XIAOYUAN_AI_CHAT: () => VIEW_TYPE_XIAOYUAN_AI_CHAT,
  default: () => XiaoyuanAIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  execMode: "hybrid",
  opencodePath: "opencode",
  serverPort: 16226,
  serverPassword: "",
  apiEndpoint: "https://api.openai.com/v1/chat/completions",
  apiKey: "",
  model: "gpt-4o",
  systemPrompt: "\u4F60\u662F\u4E00\u4E2A AI \u52A9\u624B\uFF0C\u96C6\u6210\u5728 Obsidian \u7B14\u8BB0\u8F6F\u4EF6\u4E2D\u3002\u7528\u6237\u6B63\u5728\u505A\u7B14\u8BB0\u6216\u5199\u4F5C\u3002\u8BF7\u7528\u4E2D\u6587\u56DE\u7B54\uFF0C\u4FDD\u6301\u7B80\u6D01\u4E13\u4E1A\u3002",
  maxTokens: 4096,
  temperature: 0.7,
  chatViewType: "right",
  buildMode: "build",
  level: "low",
  customApiList: [],
  defaultApiIndex: 0,
  opencodeModel: ""
};
var VIEW_TYPE_XIAOYUAN_AI_CHAT = "xiaoyuan-chat-view";
var serverProcess = null;
var serverStartPromise = null;
var EXTERNAL_SERVER = {};
async function probeServer(port) {
  return new Promise((resolve) => {
    const http = require("http");
    const req = http.get(`http://localhost:${port}/config/providers`, (res) => {
      res.on("data", () => {
      });
      res.on("end", () => {
        resolve(res.statusCode >= 200 && res.statusCode < 500);
      });
    });
    req.on("error", () => resolve(false));
    req.setTimeout(2e3, () => {
      req.destroy();
      resolve(false);
    });
  });
}
function startOpenCodeServer(opencodePath, port, password, vaultDir) {
  return new Promise(async (resolve, reject) => {
    const alive = await probeServer(port);
    if (alive) {
      serverProcess = EXTERNAL_SERVER;
      serverStartPromise = Promise.resolve();
      resolve();
      return;
    }
    try {
      const cp = require("child_process");
      const proc = cp.spawn("cmd.exe", ["/c", opencodePath, "serve", "--port", String(port)], {
        cwd: vaultDir,
        stdio: ["ignore", "pipe", "pipe"],
        env: { ...process.env, OPENCODE_SERVER_PASSWORD: password }
      });
      serverProcess = proc;
      let started = false;
      const onData = (chunk) => {
        const text = chunk.toString();
        if (!started && text.includes("listening")) {
          started = true;
          resolve();
        }
      };
      proc.stdout.on("data", onData);
      proc.stderr.on("data", onData);
      proc.on("error", (err) => {
        reject(err);
      });
      proc.on("close", (code) => {
        if (serverProcess === proc) serverProcess = null;
        if (!started) {
          serverStartPromise = null;
          reject(new Error(`opencode serve \u5F02\u5E38\u9000\u51FA\uFF08${code}\uFF09`));
        }
      });
      setTimeout(() => {
        if (!started) {
          started = true;
          resolve();
        }
      }, 15e3);
    } catch (err) {
      reject(err);
    }
  });
}
function stopOpenCodeServer() {
  if (!serverProcess || serverProcess === EXTERNAL_SERVER) {
    serverProcess = null;
    serverStartPromise = null;
    return Promise.resolve();
  }
  return new Promise((resolve) => {
    const proc = serverProcess;
    let resolved = false;
    const done = () => {
      if (!resolved) {
        resolved = true;
        serverProcess = null;
        serverStartPromise = null;
        resolve();
      }
    };
    proc.on("close", done);
    proc.on("error", done);
    try {
      proc.kill("SIGTERM");
    } catch (e) {
    }
    setTimeout(done, 3e3);
  });
}
async function httpRequest(url, options) {
  const { method = "GET", headers = {}, body } = options;
  const parsedUrl = new URL(url);
  const http = require("http");
  return new Promise((resolve, reject) => {
    const req = http.request(
      {
        hostname: parsedUrl.hostname,
        port: parsedUrl.port,
        path: parsedUrl.pathname + parsedUrl.search,
        method,
        headers
      },
      (res) => {
        const chunks = [];
        res.on("data", (chunk) => chunks.push(chunk));
        res.on("end", () => {
          var _a;
          const text = Buffer.concat(chunks).toString("utf-8");
          resolve({
            status: (_a = res.statusCode) != null ? _a : 0,
            body: async () => text,
            json: async () => JSON.parse(text)
          });
        });
      }
    );
    req.on("error", reject);
    if (body) req.write(body);
    req.end();
  });
}
async function listOpenCodeModels(port, password) {
  const baseUrl = `http://localhost:${port}`;
  const auth = Buffer.from(`opencode:${password}`).toString("base64");
  const headers = {
    Authorization: `Basic ${auth}`
  };
  try {
    const resp = await httpRequest(`${baseUrl}/models`, { method: "GET", headers });
    if (resp.status === 200) {
      const data = await resp.json();
      return data.models || [];
    }
  } catch (e) {
  }
  return [];
}
async function callOpenCodeAPI(prompt, port, password, attachments, agent, level) {
  const baseUrl = `http://localhost:${port}`;
  const auth = Buffer.from(`opencode:${password}`).toString("base64");
  const headers = {
    Authorization: `Basic ${auth}`,
    "Content-Type": "application/json"
  };
  const parts = [{ type: "text", text: prompt }];
  if (attachments) {
    for (const att of attachments) {
      if (att.type.startsWith("image/")) {
        parts.push({ type: "image", image: att.data });
      } else {
        parts.push({ type: "file", file: att.data, name: att.name });
      }
    }
  }
  const body = { parts };
  if (agent) body.agent = agent;
  if (level) body.level = level;
  const sessionResp = await httpRequest(`${baseUrl}/session`, {
    method: "POST",
    headers,
    body: JSON.stringify({ title: "xiaoyuan-plugin" })
  });
  if (sessionResp.status < 200 || sessionResp.status >= 300) {
    const txt = await sessionResp.body().catch(() => "");
    throw new Error(`\u521B\u5EFA\u4F1A\u8BDD\u5931\u8D25\uFF08${sessionResp.status}\uFF09\uFF1A${txt.slice(0, 200)}`);
  }
  const sessionData = await sessionResp.json();
  const sessionId = sessionData.id;
  try {
    const msgResp = await httpRequest(`${baseUrl}/session/${sessionId}/message`, {
      method: "POST",
      headers,
      body: JSON.stringify(body)
    });
    if (msgResp.status < 200 || msgResp.status >= 300) {
      const txt = await msgResp.body().catch(() => "");
      throw new Error(`\u53D1\u9001\u6D88\u606F\u5931\u8D25\uFF08${msgResp.status}\uFF09\uFF1A${txt.slice(0, 200)}`);
    }
    const msgData = await msgResp.json();
    const textParts = msgData.parts.filter((p) => p.type === "text" && p.text).map((p) => p.text).join("\n");
    if (textParts) return textParts;
    const anyText = msgData.parts.filter((p) => p.text).map((p) => p.text).join("\n");
    return anyText || "(\u65E0\u54CD\u5E94\u5185\u5BB9)";
  } finally {
    try {
      await httpRequest(`${baseUrl}/session/${sessionId}`, { method: "DELETE", headers });
    } catch (e) {
    }
  }
}
async function ensureServer(s, vaultDir) {
  if (serverProcess) return;
  if (serverStartPromise) {
    try {
      await serverStartPromise;
      return;
    } catch (e) {
      serverStartPromise = null;
    }
  }
  const pw = s.serverPassword || "xiaoyuan-plugin-" + Math.random().toString(36).slice(2, 10);
  if (!s.serverPassword) s.serverPassword = pw;
  const alive = await probeServer(s.serverPort);
  if (alive) {
    serverProcess = EXTERNAL_SERVER;
    return;
  }
  serverStartPromise = startOpenCodeServer(s.opencodePath, s.serverPort, pw, vaultDir).catch((err) => {
    serverStartPromise = null;
    throw err;
  });
  await serverStartPromise;
}
async function callOpenCodeCLI(prompt, settings, vaultDir, attachments) {
  await ensureServer(settings, vaultDir);
  return callOpenCodeAPI(prompt, settings.serverPort, settings.serverPassword, attachments, settings.buildMode, settings.level);
}
var XiaoyuanAIChatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.msgIdCounter = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_XIAOYUAN_AI_CHAT;
  }
  getDisplayText() {
    return "\u5C0F\u5143";
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("xiaoyuan-chat-container");
    this.viewContainer = contentEl.createDiv({ cls: "xiaoyuan-chat" });
    const headerEl = this.viewContainer.createDiv({ cls: "xiaoyuan-chat-header" });
    const leftContainer = document.createElement("span");
    leftContainer.classList.add("xiaoyuan-chat-header-left");
    const arrowLeft = document.createElement("span");
    arrowLeft.classList.add("xiaoyuan-mode-arrow");
    arrowLeft.textContent = "\u25BC";
    leftContainer.appendChild(arrowLeft);
    const modes = [
      { value: "api", label: "API" },
      { value: "hybrid", label: "\u6DF7\u5408" },
      { value: "cli", label: "CLI" }
    ];
    const modeText = this.createSelector(
      "xiaoyuan-mode-selector",
      modes,
      this.plugin.settings.execMode,
      "\u70B9\u51FB\u5207\u6362\u6267\u884C\u6A21\u5F0F",
      (value) => {
        this.plugin.settings.execMode = value;
        this.plugin.saveSettings();
        this.refresh();
      }
    );
    leftContainer.appendChild(modeText);
    headerEl.appendChild(leftContainer);
    const settingsIcon = document.createElement("span");
    settingsIcon.classList.add("xiaoyuan-settings-icon");
    settingsIcon.title = "\u8BBE\u7F6E";
    settingsIcon.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/></svg>';
    settingsIcon.addEventListener("click", () => {
      this.app.setting.open();
      this.app.setting.openTabById("xiaoyuanAI");
    });
    headerEl.appendChild(settingsIcon);
    this.messagesEl = this.viewContainer.createDiv({ cls: "xiaoyuan-chat-messages" });
    this.inputContainer = this.viewContainer.createDiv({ cls: "xiaoyuan-input-container" });
    this.inputEl = this.inputContainer.createEl("textarea", {
      cls: "xiaoyuan-chat-input",
      attr: { placeholder: "\u8F93\u5165\u4F60\u7684\u95EE\u9898..." }
    });
    const toolbarEl = this.inputContainer.createDiv({ cls: "xiaoyuan-toolbar" });
    const attachBtn = document.createElement("span");
    attachBtn.title = "\u6DFB\u52A0\u9644\u4EF6";
    attachBtn.classList.add("xiaoyuan-attach-btn");
    attachBtn.innerHTML = `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>`;
    toolbarEl.appendChild(attachBtn);
    const buildModes = [{ value: "plan", label: "plan" }, { value: "build", label: "build" }];
    const buildModeText = this.createSelector(
      "xiaoyuan-build-mode-select",
      buildModes,
      this.plugin.settings.buildMode,
      "\u70B9\u51FB\u5207\u6362\u6784\u5EFA\u6A21\u5F0F",
      (value) => {
        this.plugin.settings.buildMode = value;
        this.plugin.saveSettings();
      },
      true
    );
    toolbarEl.appendChild(buildModeText);
    const modelText = this.createModelSelector();
    toolbarEl.appendChild(modelText);
    const levels = [
      { value: "low", label: "low" },
      { value: "medium", label: "medium" },
      { value: "high", label: "high" },
      { value: "max", label: "max" }
    ];
    const levelText = this.createSelector(
      "xiaoyuan-level-select",
      levels,
      this.plugin.settings.level,
      "\u70B9\u51FB\u5207\u6362\u7EA7\u522B",
      (value) => {
        this.plugin.settings.level = value;
        this.plugin.saveSettings();
      },
      true
    );
    toolbarEl.appendChild(levelText);
    this.sendBtn = this.createSendButton();
    this.sendBtn.classList.add("xiaoyuan-send-btn-right");
    this.sendBtn.addEventListener("click", () => this.sendMessage());
    toolbarEl.appendChild(this.sendBtn);
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.addWelcomeMessage();
  }
  createModelSelector() {
    var _a, _b;
    const s = this.plugin.settings;
    let models = [];
    let currentModel = "";
    if (s.execMode === "hybrid") {
      if (s.customApiList.length > 0) {
        models = s.customApiList.map((api) => ({ value: api.model, label: api.model }));
        currentModel = ((_a = s.customApiList[s.defaultApiIndex]) == null ? void 0 : _a.model) || "";
      } else {
        models = [{ value: s.model, label: s.model }];
        currentModel = s.model;
      }
    } else if (s.execMode === "api") {
      if (s.customApiList.length > 0) {
        models = s.customApiList.map((api) => ({ value: api.model, label: api.model }));
        currentModel = ((_b = s.customApiList[s.defaultApiIndex]) == null ? void 0 : _b.model) || "";
      } else {
        models = [{ value: s.model, label: s.model }];
        currentModel = s.model;
      }
    } else {
      models = s.opencodeModel ? [{ value: s.opencodeModel, label: s.opencodeModel }] : [{ value: "", label: "\u52A0\u8F7D\u4E2D..." }];
      currentModel = s.opencodeModel;
    }
    const selector = this.createSelector(
      "xiaoyuan-model-select",
      models,
      currentModel,
      "\u70B9\u51FB\u5207\u6362\u6A21\u578B",
      (value) => {
        if (s.execMode === "cli") {
          s.opencodeModel = value;
        } else {
          const idx = s.customApiList.findIndex((api) => api.model === value);
          if (idx >= 0) {
            s.defaultApiIndex = idx;
          } else {
            s.model = value;
          }
        }
        this.plugin.saveSettings();
      },
      true
    );
    if (s.execMode === "cli") {
      const originalListener = selector.onclick;
      selector.onclick = async (e) => {
        e.stopPropagation();
        document.querySelectorAll(".xiaoyuan-mode-dropdown").forEach((el) => el.remove());
        try {
          const alive = await probeServer(s.serverPort);
          if (alive) {
            const openCodeModels = await listOpenCodeModels(s.serverPort, s.serverPassword);
            const newModels = openCodeModels.map((m) => ({ value: m, label: m }));
            if (JSON.stringify(newModels) !== JSON.stringify(models)) {
              models = newModels;
              if (!s.opencodeModel || !openCodeModels.includes(s.opencodeModel)) {
                s.opencodeModel = openCodeModels[0] || "";
                await this.plugin.saveSettings();
              }
              currentModel = s.opencodeModel;
              const parent = selector.parentElement;
              if (parent) {
                const newSelector = this.createSelector(
                  "xiaoyuan-model-select",
                  models,
                  currentModel,
                  "\u70B9\u51FB\u5207\u6362\u6A21\u578B",
                  (value) => {
                    s.opencodeModel = value;
                    this.plugin.saveSettings();
                  },
                  true
                );
                newSelector.onclick = selector.onclick;
                parent.replaceChild(newSelector, selector);
                newSelector.click();
                return;
              }
            }
          }
        } catch (e2) {
        }
        if (originalListener) {
          const event = new MouseEvent("click", { bubbles: true, cancelable: true });
          selector.dispatchEvent(event);
        }
      };
    }
    return selector;
  }
  createSelector(className, options, currentValue, title, onChange, dropdownUp = false) {
    var _a;
    const text = document.createElement("span");
    text.classList.add(className);
    const currentOption = options.find((m) => m.value === currentValue);
    text.textContent = (currentOption == null ? void 0 : currentOption.label) || ((_a = options[0]) == null ? void 0 : _a.label) || "";
    text.setAttribute("title", title);
    text.addEventListener("click", (e) => {
      e.stopPropagation();
      document.querySelectorAll(".xiaoyuan-mode-dropdown").forEach((el) => el.remove());
      const dropdown = document.createElement("div");
      dropdown.classList.add("xiaoyuan-mode-dropdown");
      if (dropdownUp) dropdown.classList.add("xiaoyuan-mode-dropdown-up");
      options.forEach((m) => {
        const item = document.createElement("div");
        item.classList.add("xiaoyuan-mode-dropdown-item");
        if (m.value === currentValue) item.classList.add("active");
        item.textContent = m.label;
        item.addEventListener("click", () => {
          text.textContent = m.label;
          onChange(m.value);
          dropdown.remove();
        });
        dropdown.appendChild(item);
      });
      text.appendChild(dropdown);
      const closeDropdown = (ev) => {
        if (!dropdown.contains(ev.target)) {
          dropdown.remove();
          document.removeEventListener("click", closeDropdown);
        }
      };
      setTimeout(() => document.addEventListener("click", closeDropdown), 0);
    });
    return text;
  }
  createSendButton() {
    const btn = document.createElement("button");
    btn.title = "\u53D1\u9001";
    btn.classList.add("xiaoyuan-send-btn");
    btn.innerHTML = `<svg width="16" height="16" viewBox="0 0 24 24" fill="none"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z" fill="currentColor"/></svg>`;
    return btn;
  }
  addWelcomeMessage() {
    const s = this.plugin.settings;
    const modeInfo = s.execMode === "cli" ? `\u5F53\u524D\u6A21\u5F0F\uFF1ACLI\uFF08opencode serve\uFF09` : s.execMode === "hybrid" ? `\u5F53\u524D\u6A21\u5F0F\uFF1A\u6DF7\u5408\uFF08\u64CD\u4F5C\u2192CLI, \u804A\u5929\u2192API\uFF09` : `\u5F53\u524D\u6A21\u5F0F\uFF1AAPI\uFF08\u76F4\u63A5\u8C03\u7528\uFF09`;
    const msgEl = this.messagesEl.createDiv({ cls: "xiaoyuan-msg xiaoyuan-msg-assistant xiaoyuan-welcome" });
    const bubble = msgEl.createDiv({ cls: "xiaoyuan-msg-bubble" });
    bubble.innerHTML = `\u{1F44B} \u4F60\u597D\uFF01\u6211\u662F\u5C0F\u5143\u3002<br><br>${modeInfo}<br><br>\u6211\u53EF\u4EE5\u5E2E\u4F60\uFF1A<br>\u2022 \u{1F4AC} \u804A\u5929\u5BF9\u8BDD<br>\u2022 \u270D\uFE0F \u6DA6\u8272\u3001\u603B\u7ED3\u3001\u8865\u5168\u7B14\u8BB0<br>\u2022 \u{1F50D} \u67E5\u8BE2\u7EF4\u57FA\u77E5\u8BC6<br><br>\u9009\u4E2D\u6587\u672C\u540E\u53F3\u952E \u2192 \u4F7F\u7528 AI \u64CD\u4F5C\u3002`;
  }
  async sendMessage() {
    const text = this.inputEl.value.trim();
    if (!text) return;
    this.addMessage("user", text);
    this.inputEl.value = "";
    this.disableInput(true);
    try {
      const response = await this.callAI(text);
      this.addMessage("assistant", response);
    } catch (err) {
      this.addMessage("assistant", `\u274C \u9519\u8BEF\uFF1A${err.message}`);
    } finally {
      this.disableInput(false);
      this.inputEl.focus();
    }
  }
  addMessage(role, content) {
    const id = "msg-" + ++this.msgIdCounter;
    this.messages.push({ id, role, content });
    const msgEl = this.messagesEl.createDiv({ cls: `xiaoyuan-msg xiaoyuan-msg-${role}` });
    msgEl.id = id;
    const bubbleEl = msgEl.createDiv({ cls: "xiaoyuan-msg-bubble" });
    if (role === "user") {
      const textEl = bubbleEl.createSpan();
      textEl.textContent = content;
      const undoBtn = msgEl.createSpan({ cls: "xiaoyuan-msg-action xiaoyuan-undo-btn" });
      undoBtn.textContent = "\u21A9";
      undoBtn.title = "\u64A4\u9500\u6B64\u6D88\u606F";
      undoBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.undoMessage(id);
      });
    } else {
      bubbleEl.innerHTML = this.renderMarkdown(content.trim());
      const actionsEl = msgEl.createDiv({ cls: "xiaoyuan-msg-actions" });
      const copyBtn = actionsEl.createSpan({ cls: "xiaoyuan-msg-action" });
      copyBtn.textContent = "\u{1F4CB}";
      copyBtn.title = "\u590D\u5236";
      copyBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(content);
        new import_obsidian.Notice("\u5DF2\u590D\u5236");
      });
    }
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
  undoMessage(id) {
    const idx = this.messages.findIndex((m) => m.id === id);
    if (idx === -1) return;
    this.messages = this.messages.slice(0, idx);
    const msgEls = this.messagesEl.querySelectorAll(".xiaoyuan-msg");
    for (let i = msgEls.length - 1; i >= idx; i--) {
      msgEls[i].remove();
    }
    new import_obsidian.Notice("\u5DF2\u64A4\u9500");
  }
  renderMarkdown(text) {
    const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    let h = esc(text);
    h = h.replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code class="language-$1">$2</code></pre>').replace(/`([^`]+)`/g, "<code>$1</code>").replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>").replace(/\*([^*]+)\*/g, "<em>$1</em>").replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank">$1</a>').replace(/^- (.+)$/gm, "\u2022 $1").replace(/\n/g, "<br>");
    return h;
  }
  async callAI(userMessage) {
    var _a, _b, _c;
    const s = this.plugin.settings;
    if (s.execMode === "cli") {
      const vaultDir = this.app.vault.adapter.getBasePath();
      const allMessages = [
        { role: "system", content: s.systemPrompt },
        ...this.messages.map((m) => ({ role: m.role, content: m.content })),
        { role: "user", content: userMessage }
      ];
      const prompt = allMessages.map((m) => `${m.role === "system" ? "[\u7CFB\u7EDF]" : m.role === "user" ? "[\u7528\u6237]" : "[\u52A9\u624B]"}: ${m.content}`).join("\n\n");
      return callOpenCodeCLI(prompt, s, vaultDir);
    }
    const apiConfig = s.customApiList.length > 0 ? s.customApiList[s.defaultApiIndex] : null;
    const endpoint = (apiConfig == null ? void 0 : apiConfig.endpoint) || s.apiEndpoint;
    const apiKey = (apiConfig == null ? void 0 : apiConfig.apiKey) || s.apiKey;
    const model = (apiConfig == null ? void 0 : apiConfig.model) || s.model;
    if (!apiKey) throw new Error("API Key \u672A\u914D\u7F6E\u3002\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199\u3002");
    const body = {
      model,
      messages: [
        { role: "system", content: s.systemPrompt },
        ...this.messages.map((m) => ({ role: m.role, content: m.content })),
        { role: "user", content: userMessage }
      ],
      max_tokens: s.maxTokens,
      temperature: s.temperature,
      stream: false
    };
    const resp = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
      body: JSON.stringify(body)
    });
    if (!resp.ok) {
      const errText = await resp.text().catch(() => "");
      throw new Error(`API ${resp.status}: ${errText.slice(0, 200)}`);
    }
    const data = await resp.json();
    return ((_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "\uFF08\u65E0\u54CD\u5E94\uFF09";
  }
  disableInput(disabled) {
    this.inputEl.disabled = disabled;
    this.sendBtn.disabled = disabled;
    if (disabled) {
      this.sendBtn.classList.add("disabled");
    } else {
      this.sendBtn.classList.remove("disabled");
    }
  }
  refresh() {
    this.messages = [];
    this.messagesEl.empty();
    this.addWelcomeMessage();
  }
  async onClose() {
    this.viewContainer.empty();
  }
};
var OPERATION_PROMPTS = {
  polish: "\u4F60\u662F\u4E00\u4E2A\u6587\u5B57\u6DA6\u8272\u52A9\u624B\u3002\u8BF7\u6DA6\u8272\u4EE5\u4E0B\u6587\u672C\uFF0C\u6539\u8FDB\u8868\u8FBE\u3001\u8BED\u6CD5\u548C\u6D41\u7545\u5EA6\uFF0C\u4FDD\u6301\u539F\u610F\u4E0D\u53D8\u3002\u53EA\u8F93\u51FA\u6DA6\u8272\u540E\u7684\u7ED3\u679C\uFF0C\u4E0D\u8981\u6DFB\u52A0\u4EFB\u4F55\u89E3\u91CA\uFF1A\n\n",
  summarize: "\u4F60\u662F\u4E00\u4E2A\u603B\u7ED3\u52A9\u624B\u3002\u8BF7\u5BF9\u4EE5\u4E0B\u6587\u672C\u8FDB\u884C\u7B80\u6D01\u7684\u603B\u7ED3\uFF0C\u63D0\u53D6\u5173\u952E\u8981\u70B9\u3002\u7528\u4E2D\u6587\u603B\u7ED3\uFF0C\u53EA\u8F93\u51FA\u603B\u7ED3\u5185\u5BB9\uFF1A\n\n",
  complete: "\u4F60\u662F\u4E00\u4E2A\u5199\u4F5C\u52A9\u624B\u3002\u8BF7\u6839\u636E\u4E0A\u4E0B\u6587\uFF0C\u81EA\u7136\u5730\u8865\u5168\u4EE5\u4E0B\u5185\u5BB9\uFF0C\u4FDD\u6301\u98CE\u683C\u4E00\u81F4\uFF1A\n\n",
  expand: "\u4F60\u662F\u4E00\u4E2A\u5199\u4F5C\u52A9\u624B\u3002\u8BF7\u6269\u5199\u4EE5\u4E0B\u5185\u5BB9\uFF0C\u589E\u52A0\u7EC6\u8282\u3001\u4F8B\u5B50\u548C\u6DF1\u5EA6\uFF0C\u4FDD\u7559\u539F\u6587\u7684\u6838\u5FC3\u89C2\u70B9\uFF1A\n\n",
  translate: "\u4F60\u662F\u4E00\u4E2A\u7FFB\u8BD1\u52A9\u624B\u3002\u8BF7\u5C06\u4EE5\u4E0B\u6587\u672C\u7FFB\u8BD1\u6210\u4E2D\u6587\uFF0C\u4FDD\u6301\u4E13\u4E1A\u6027\u548C\u6D41\u7545\u5EA6\uFF1A\n\n",
  continue: "\u4F60\u662F\u4E00\u4E2A\u5199\u4F5C\u52A9\u624B\u3002\u8BF7\u6839\u636E\u4EE5\u4E0B\u5185\u5BB9\u81EA\u7136\u5730\u7EED\u5199\uFF0C\u4FDD\u6301\u98CE\u683C\u4E00\u81F4\uFF1A\n\n"
};
var OPERATION_LABELS = {
  polish: "\u6DA6\u8272",
  summarize: "\u603B\u7ED3",
  complete: "\u8865\u5168",
  expand: "\u6269\u5199",
  translate: "\u7FFB\u8BD1\u4E3A\u4E2D\u6587",
  continue: "\u7EED\u5199"
};
var TextOperationModal = class extends import_obsidian.Modal {
  constructor(app, plugin, operation, inputText) {
    super(app);
    this.plugin = plugin;
    this.operation = operation;
    this.inputText = inputText;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.classList.add("xiaoyuan-modal-container");
    const headerRow = contentEl.createDiv({ cls: "xiaoyuan-modal-header" });
    headerRow.createEl("h3", { text: `AI ${OPERATION_LABELS[this.operation] || this.operation}` });
    this.modeLabel = headerRow.createSpan({ cls: "xiaoyuan-modal-mode-label" });
    this.modeLabel.textContent = this.plugin.settings.execMode === "cli" ? "CLI" : "API";
    this.loadingEl = contentEl.createDiv({ cls: "xiaoyuan-modal-loading", text: "\u23F3 \u5904\u7406\u4E2D..." });
    this.resultEl = contentEl.createDiv({ cls: "xiaoyuan-modal-result" });
    this.processOperation();
  }
  async processOperation() {
    var _a, _b, _c;
    try {
      const s = this.plugin.settings;
      const prompt = (OPERATION_PROMPTS[this.operation] || OPERATION_PROMPTS.polish) + this.inputText;
      let result;
      if (s.execMode === "cli" || s.execMode === "hybrid") {
        this.modeLabel.textContent = "CLI";
        const vaultDir = this.app.vault.adapter.getBasePath();
        result = await callOpenCodeCLI(prompt, s, vaultDir);
      } else {
        this.modeLabel.textContent = "API";
        if (!s.apiKey) {
          new import_obsidian.Notice("API Key \u672A\u914D\u7F6E");
          this.close();
          return;
        }
        const resp = await fetch(s.apiEndpoint, {
          method: "POST",
          headers: { "Content-Type": "application/json", Authorization: `Bearer ${s.apiKey}` },
          body: JSON.stringify({
            model: s.model,
            messages: [{ role: "user", content: prompt }],
            max_tokens: s.maxTokens,
            temperature: s.temperature,
            stream: false
          })
        });
        if (!resp.ok) throw new Error(`API ${resp.status}`);
        const data = await resp.json();
        result = ((_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "\uFF08\u65E0\u54CD\u5E94\uFF09";
      }
      this.loadingEl.classList.add("hidden");
      this.resultEl.classList.add("show");
      this.resultEl.textContent = result;
      const btnRow = this.contentEl.createDiv({ cls: "xiaoyuan-modal-btn-row" });
      const replaceBtn = btnRow.createEl("button", { text: "\u66FF\u6362\u539F\u6587", cls: "xiaoyuan-btn-primary" });
      replaceBtn.addEventListener("click", () => {
        const editor = this.plugin.getActiveEditor();
        if (editor) {
          editor.replaceSelection(result);
          new import_obsidian.Notice("\u5DF2\u66FF\u6362");
        } else new import_obsidian.Notice("\u672A\u627E\u5230\u6D3B\u52A8\u7F16\u8F91\u5668");
        this.close();
      });
      const copyBtn = btnRow.createEl("button", { text: "\u590D\u5236\u7ED3\u679C", cls: "xiaoyuan-btn-secondary" });
      copyBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(result);
        new import_obsidian.Notice("\u5DF2\u590D\u5236");
      });
      const closeBtn = btnRow.createEl("button", { text: "\u5173\u95ED", cls: "xiaoyuan-btn-secondary" });
      closeBtn.addEventListener("click", () => this.close());
    } catch (err) {
      this.loadingEl.textContent = `\u274C \u9519\u8BEF\uFF1A${err.message}`;
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var WIKI_SYSTEM_PROMPTS = {
  query: "\u4F60\u662F\u4E00\u4E2A\u7EF4\u57FA\u77E5\u8BC6\u5E93\u7684\u68C0\u7D22\u52A9\u624B\u3002\u6839\u636E\u7528\u6237\u7684\u95EE\u9898\uFF0C\u4ECE\u77E5\u8BC6\u5E93\u89D2\u5EA6\u7ED9\u51FA\u7EFC\u5408\u6027\u7684\u56DE\u7B54\u3002\u5982\u679C\u4E0D\u77E5\u9053\uFF0C\u5C31\u8BDA\u5B9E\u8BF4\u4E0D\u77E5\u9053\u3002",
  capture: "\u4F60\u6B63\u5728\u5C06\u7528\u6237\u63D0\u4F9B\u7684\u5185\u5BB9\u6574\u7406\u4E3A\u7EF4\u57FA\u7B14\u8BB0\u3002\u8BF7\u63D0\u53D6\u5173\u952E\u4FE1\u606F\uFF0C\u5206\u7C7B\uFF08concept/skill/reference/decision\uFF09\uFF0C\u8F93\u51FA\u5E26 YAML frontmatter \u7684 Obsidian Markdown \u683C\u5F0F\u3002",
  ingest: "\u4F60\u6B63\u5728\u6444\u5165\u6587\u6863\u3002\u8BF7\u5206\u6790\u5185\u5BB9\uFF0C\u84B8\u998F\u51FA\u6838\u5FC3\u6982\u5FF5\u3001\u5B9E\u4F53\u3001\u6280\u80FD\uFF0C\u7528\u4E2D\u6587\u8F93\u51FA\u591A\u4E2A\u7EF4\u57FA\u9875\u9762\uFF08\u5E26 frontmatter \u548C [[\u7EF4\u57FA\u94FE\u63A5]]\uFF09\u3002"
};
var WikiCommandModal = class extends import_obsidian.Modal {
  constructor(app, plugin, command) {
    super(app);
    this.plugin = plugin;
    this.command = command;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.classList.add("xiaoyuan-wiki-modal-container");
    contentEl.createEl("h3", { text: `\u{1F9E0} Wiki \u547D\u4EE4\uFF1A/${this.command}` });
    const inputEl = contentEl.createEl("textarea", {
      cls: "xiaoyuan-wiki-input",
      attr: { placeholder: this.command === "query" ? "\u8F93\u5165\u67E5\u8BE2\u5185\u5BB9..." : "\u8F93\u5165\u8981\u4FDD\u5B58\u7684\u5185\u5BB9..." }
    });
    const btnRow = contentEl.createDiv({ cls: "xiaoyuan-wiki-btn-row" });
    const submitBtn = btnRow.createEl("button", { text: "\u6267\u884C", cls: "xiaoyuan-btn-primary" });
    const resultEl = contentEl.createDiv({ cls: "xiaoyuan-wiki-result" });
    submitBtn.addEventListener("click", async () => {
      var _a, _b, _c;
      const text = inputEl.value.trim();
      if (!text) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u5185\u5BB9");
        return;
      }
      submitBtn.disabled = true;
      submitBtn.textContent = "\u5904\u7406\u4E2D...";
      try {
        const s = this.plugin.settings;
        const systemPrompt = WIKI_SYSTEM_PROMPTS[this.command] || "";
        let result;
        if (s.execMode === "cli" || s.execMode === "hybrid") {
          const fullPrompt = systemPrompt ? `${systemPrompt}

---
${text}` : text;
          const vaultDir = this.app.vault.adapter.getBasePath();
          result = await callOpenCodeCLI(fullPrompt, s, vaultDir);
        } else {
          if (!s.apiKey) {
            new import_obsidian.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Key");
            return;
          }
          const resp = await fetch(s.apiEndpoint, {
            method: "POST",
            headers: { "Content-Type": "application/json", Authorization: `Bearer ${s.apiKey}` },
            body: JSON.stringify({
              model: s.model,
              messages: [
                ...systemPrompt ? [{ role: "system", content: systemPrompt }] : [],
                { role: "user", content: text }
              ],
              max_tokens: s.maxTokens,
              temperature: s.temperature,
              stream: false
            })
          });
          const data = await resp.json();
          result = ((_c = (_b = (_a = data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) || "\uFF08\u65E0\u54CD\u5E94\uFF09";
        }
        resultEl.classList.add("show");
        resultEl.textContent = result;
      } catch (err) {
        resultEl.classList.add("show");
        resultEl.textContent = `\u274C \u9519\u8BEF\uFF1A${err.message}`;
      } finally {
        submitBtn.disabled = false;
        submitBtn.textContent = "\u6267\u884C";
      }
    });
    const closeBtn = btnRow.createEl("button", { text: "\u5173\u95ED", cls: "xiaoyuan-btn-secondary" });
    closeBtn.addEventListener("click", () => this.close());
  }
};
var XiaoyuanAISettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5C0F\u5143 \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u6267\u884C\u6A21\u5F0F").setDesc("\u9009\u62E9\u5982\u4F55\u8C03\u7528 AI \u80FD\u529B").addDropdown((dd) => {
      dd.addOption("hybrid", "\u{1F310} \u6DF7\u5408\u6A21\u5F0F\uFF08\u64CD\u4F5C\u2192CLI, \u804A\u5929\u2192API\uFF09");
      dd.addOption("cli", "\u{1F4BB} CLI \u6A21\u5F0F\uFF08\u5168\u90E8\u901A\u8FC7 opencode serve\uFF09");
      dd.addOption("api", "\u2601\uFE0F API \u6A21\u5F0F\uFF08\u76F4\u63A5\u8C03\u7528 API\uFF09");
      dd.setValue(this.plugin.settings.execMode);
      dd.onChange(async (val) => {
        this.plugin.settings.execMode = val;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const s = this.plugin.settings;
    if (s.execMode === "cli" || s.execMode === "hybrid") {
      containerEl.createEl("h3", { text: "CLI \u914D\u7F6E" });
      new import_obsidian.Setting(containerEl).setName("opencode \u8DEF\u5F84").setDesc("opencode \u53EF\u6267\u884C\u6587\u4EF6\u8DEF\u5F84\u3002\u5168\u5C40\u5B89\u88C5\u586B opencode \u5373\u53EF\u3002").addText(
        (text) => text.setPlaceholder("opencode").setValue(s.opencodePath).onChange(async (val) => {
          s.opencodePath = val;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian.Setting(containerEl).setName("\u670D\u52A1\u5668\u7AEF\u53E3").setDesc("opencode serve \u7684\u76D1\u542C\u7AEF\u53E3").addText(
        (text) => text.setPlaceholder("16226").setValue(String(s.serverPort)).onChange(async (val) => {
          const n = parseInt(val);
          if (n > 0 && n < 65536) {
            s.serverPort = n;
            await this.plugin.saveSettings();
          }
        })
      );
      new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u6784\u5EFA\u6A21\u5F0F").setDesc("plan = \u89C4\u5212\u4F18\u5148\uFF0Cbuild = \u76F4\u63A5\u6267\u884C").addDropdown((dd) => {
        dd.addOption("plan", "plan");
        dd.addOption("build", "build");
        dd.setValue(s.buildMode);
        dd.onChange(async (val) => {
          s.buildMode = val;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u7EA7\u522B").setDesc("opencode \u7684\u6267\u884C\u7EA7\u522B\uFF08low / medium / high / max\uFF09").addDropdown((dd) => {
        dd.addOption("low", "low");
        dd.addOption("medium", "medium");
        dd.addOption("high", "high");
        dd.addOption("max", "max");
        dd.setValue(s.level);
        dd.onChange(async (val) => {
          s.level = val;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u6A21\u578B").setDesc("\u8BBE\u7F6E CLI \u6A21\u5F0F\u4E0B\u4F7F\u7528\u7684\u6A21\u578B\uFF08\u4ECE OpenCode \u8BFB\u53D6\uFF09").addDropdown((dd) => {
        dd.addOption("", "\u52A0\u8F7D\u4E2D...");
        dd.onChange(async (val) => {
          s.opencodeModel = val;
          await this.plugin.saveSettings();
        });
        (async () => {
          try {
            const alive = await probeServer(s.serverPort);
            if (alive) {
              const models = await listOpenCodeModels(s.serverPort, s.serverPassword);
              const selectEl = dd.selectEl;
              if (selectEl) {
                selectEl.innerHTML = "";
                if (models.length > 0) {
                  models.forEach((m) => {
                    const opt = document.createElement("option");
                    opt.value = m;
                    opt.textContent = m;
                    selectEl.appendChild(opt);
                  });
                  if (s.opencodeModel && models.includes(s.opencodeModel)) {
                    selectEl.value = s.opencodeModel;
                  } else {
                    selectEl.value = models[0];
                    s.opencodeModel = models[0];
                    await this.plugin.saveSettings();
                  }
                } else {
                  const opt = document.createElement("option");
                  opt.value = "";
                  opt.textContent = "\u65E0\u53EF\u7528\u6A21\u578B";
                  selectEl.appendChild(opt);
                }
              }
            } else {
              const selectEl = dd.selectEl;
              if (selectEl) {
                selectEl.innerHTML = "";
                const opt = document.createElement("option");
                opt.value = "";
                opt.textContent = "\u8BF7\u5148\u542F\u52A8\u670D\u52A1\u5668";
                selectEl.appendChild(opt);
              }
            }
          } catch (e) {
            const selectEl = dd.selectEl;
            if (selectEl) {
              selectEl.innerHTML = "";
              const opt = document.createElement("option");
              opt.value = "";
              opt.textContent = "\u8BFB\u53D6\u5931\u8D25";
              selectEl.appendChild(opt);
            }
          }
        })();
      });
      new import_obsidian.Setting(containerEl).setName("\u6D4B\u8BD5 CLI \u8FDE\u63A5").setDesc("\u542F\u52A8/\u6D4B\u8BD5 opencode serve \u662F\u5426\u6B63\u5E38").addButton((btn) => {
        btn.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5");
        btn.onClick(async () => {
          btn.disabled = true;
          btn.setButtonText("\u68C0\u6D4B\u4E2D...");
          try {
            const pw = s.serverPassword || "xiaoyuan-plugin-" + Math.random().toString(36).slice(2, 10);
            if (!s.serverPassword) {
              s.serverPassword = pw;
              await this.plugin.saveSettings();
            }
            const alive = await probeServer(s.serverPort);
            if (alive) {
              new import_obsidian.Notice("\u2705 \u68C0\u6D4B\u5230\u5DF2\u6709\u670D\u52A1\u5668\u5728\u8FD0\u884C");
              btn.setButtonText("\u5DF2\u6709\u670D\u52A1");
              return;
            }
            btn.setButtonText("\u542F\u52A8\u4E2D...");
            const vaultDir = this.app.vault.adapter.getBasePath();
            await startOpenCodeServer(s.opencodePath, s.serverPort, pw, vaultDir);
            const result = await callOpenCodeAPI("\u56DE\u590D OK", s.serverPort, pw);
            new import_obsidian.Notice(`\u2705 opencode \u8FDE\u63A5\u6210\u529F\uFF1A${result}`);
          } catch (err) {
            new import_obsidian.Notice(`\u274C CLI \u5931\u8D25\uFF1A${err.message}`);
          } finally {
            btn.disabled = false;
            btn.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5");
          }
        });
      });
    }
    if (s.execMode === "api" || s.execMode === "hybrid") {
      containerEl.createEl("h3", { text: "API \u914D\u7F6E" });
      new import_obsidian.Setting(containerEl).setName("\u81EA\u5B9A\u4E49 API \u914D\u7F6E").setDesc("\u7BA1\u7406\u591A\u4E2A API \u914D\u7F6E").addButton((btn) => {
        btn.setButtonText("\u6DFB\u52A0\u914D\u7F6E");
        btn.onClick(() => {
          s.customApiList.push({ name: `API ${s.customApiList.length + 1}`, endpoint: "", apiKey: "", model: "gpt-4o" });
          this.plugin.saveSettings();
          this.display();
        });
      });
      s.customApiList.forEach((api, index) => {
        const apiSetting = new import_obsidian.Setting(containerEl).setName(`\u914D\u7F6E ${index + 1}: ${api.name}`).setDesc(api.endpoint || "\u672A\u8BBE\u7F6E\u7AEF\u70B9");
        apiSetting.controlEl.style.marginBottom = "0";
        new import_obsidian.Setting(containerEl).setName(`API ${index + 1} \u540D\u79F0`).addText(
          (text) => text.setPlaceholder("API \u540D\u79F0").setValue(api.name).onChange(async (val) => {
            s.customApiList[index].name = val;
            await this.plugin.saveSettings();
            this.display();
          })
        );
        new import_obsidian.Setting(containerEl).setName(`API ${index + 1} \u7AEF\u70B9`).addText(
          (text) => text.setPlaceholder("https://api.openai.com/v1/chat/completions").setValue(api.endpoint).onChange(async (val) => {
            s.customApiList[index].endpoint = val;
            await this.plugin.saveSettings();
          })
        );
        new import_obsidian.Setting(containerEl).setName(`API ${index + 1} Key`).addText((text) => {
          text.setPlaceholder("sk-...").setValue(api.apiKey);
          text.inputEl.type = "password";
          text.onChange(async (val) => {
            s.customApiList[index].apiKey = val;
            await this.plugin.saveSettings();
          });
        });
        new import_obsidian.Setting(containerEl).setName(`API ${index + 1} \u6A21\u578B`).addText(
          (text) => text.setPlaceholder("gpt-4o").setValue(api.model).onChange(async (val) => {
            s.customApiList[index].model = val;
            await this.plugin.saveSettings();
          })
        );
        new import_obsidian.Setting(containerEl).setName("").addButton((btn) => {
          btn.setButtonText("\u5220\u9664");
          btn.onClick(async () => {
            s.customApiList.splice(index, 1);
            if (s.defaultApiIndex >= s.customApiList.length) {
              s.defaultApiIndex = Math.max(0, s.customApiList.length - 1);
            }
            await this.plugin.saveSettings();
            this.display();
          });
        });
        containerEl.createEl("hr", { cls: "xiaoyuan-setting-hr" });
      });
      if (s.customApiList.length > 0) {
        new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4 API \u914D\u7F6E").setDesc("\u9009\u62E9\u9ED8\u8BA4\u4F7F\u7528\u7684 API \u914D\u7F6E").addDropdown((dd) => {
          s.customApiList.forEach((api, i) => {
            dd.addOption(String(i), api.name);
          });
          dd.setValue(String(s.defaultApiIndex));
          dd.onChange(async (val) => {
            s.defaultApiIndex = parseInt(val);
            await this.plugin.saveSettings();
          });
        });
      }
      new import_obsidian.Setting(containerEl).setName("\u7CFB\u7EDF\u63D0\u793A\u8BCD").addTextArea((text) => {
        text.setValue(s.systemPrompt);
        text.inputEl.rows = 4;
        text.onChange(async (val) => {
          s.systemPrompt = val;
          await this.plugin.saveSettings();
        });
      });
      new import_obsidian.Setting(containerEl).setName("\u6700\u5927 Token \u6570").addText(
        (text) => text.setPlaceholder("4096").setValue(String(s.maxTokens)).onChange(async (val) => {
          const n = parseInt(val);
          if (n > 0) {
            s.maxTokens = n;
            await this.plugin.saveSettings();
          }
        })
      );
      new import_obsidian.Setting(containerEl).setName("\u6E29\u5EA6").addSlider(
        (slider) => slider.setLimits(0, 2, 0.1).setValue(s.temperature).onChange(async (val) => {
          s.temperature = val;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "\u5E2E\u52A9" });
    const help = containerEl.createDiv();
    help.innerHTML = `
      <p><strong>\u6267\u884C\u6A21\u5F0F\u8BF4\u660E\uFF1A</strong></p>
      <p>\u2022 <strong>\u6DF7\u5408\u6A21\u5F0F\uFF08\u9ED8\u8BA4\uFF09</strong>\uFF1A\u6587\u672C\u64CD\u4F5C\u548C Wiki \u547D\u4EE4\u8D70 opencode serve\uFF0C\u804A\u5929\u8D70 API\u3002\u6700\u4F73\u4F53\u9A8C\u3002</p>
      <p>\u2022 <strong>CLI \u6A21\u5F0F</strong>\uFF1A\u6240\u6709\u64CD\u4F5C\u901A\u8FC7 opencode serve \u6267\u884C\u3002</p>
      <p>\u2022 <strong>API \u6A21\u5F0F</strong>\uFF1A\u6240\u6709\u64CD\u4F5C\u76F4\u63A5\u8C03\u7528 API\u3002</p>
      <p><strong>\u6587\u672C\u64CD\u4F5C\uFF1A</strong>\u5728\u7F16\u8F91\u5668\u4E2D\u9009\u4E2D\u6587\u672C \u2192 \u53F3\u952E \u2192 "\u4F7F\u7528 AI" \u5B50\u83DC\u5355</p>
      <p><strong>\u804A\u5929\uFF1A</strong>\u70B9\u51FB\u5DE6\u4FA7 Ribbon \u680F\u7684 \u{1F4AC} \u56FE\u6807\u6253\u5F00\u804A\u5929\u9762\u677F</p>
      <p><strong>Wiki \u547D\u4EE4\uFF1A</strong>\u901A\u8FC7\u547D\u4EE4\u9762\u677F\u641C\u7D22 "\u5C0F\u5143" \u627E\u5230\u7EF4\u57FA\u547D\u4EE4</p>
    `;
    help.classList.add("xiaoyuan-help-text");
  }
};
var XiaoyuanAIPlugin = class extends import_obsidian.Plugin {
  async onload() {
    serverProcess = null;
    serverStartPromise = null;
    await this.loadSettings();
    this.registerView(VIEW_TYPE_XIAOYUAN_AI_CHAT, (leaf) => new XiaoyuanAIChatView(leaf, this));
    this.addRibbonIcon("message-circle", "\u5C0F\u5143", () => this.activateChatView());
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const sel = editor.getSelection();
        if (!sel) return;
        const ops = ["polish", "summarize", "complete", "expand", "translate", "continue"];
        ops.forEach((op) => {
          menu.addItem((item) => {
            item.setTitle(`AI ${OPERATION_LABELS[op]}`);
            item.setIcon(op === "polish" ? "pencil" : op === "summarize" ? "align-justify" : "plus");
            item.onClick(() => new TextOperationModal(this.app, this, op, sel).open());
          });
        });
      })
    );
    this.addCommand({ id: "xiaoyuanAI-toggle-chat", name: "\u5207\u6362\u5C0F\u5143\u804A\u5929\u9762\u677F", callback: () => this.activateChatView() });
    ["polish", "summarize", "complete", "expand", "translate", "continue"].forEach((op) => {
      this.addCommand({
        id: `xiaoyuanAI-${op}`,
        name: `AI ${OPERATION_LABELS[op]}\u9009\u4E2D\u6587\u672C`,
        editorCallback: (editor) => {
          const text = editor.getSelection();
          if (text) new TextOperationModal(this.app, this, op, text).open();
        }
      });
    });
    this.addCommand({ id: "xiaoyuanAI-wiki-query", name: "\u{1F50D} Wiki \u67E5\u8BE2", callback: () => new WikiCommandModal(this.app, this, "query").open() });
    this.addCommand({ id: "xiaoyuanAI-wiki-capture", name: "\u{1F4E5} Wiki \u6355\u6349", callback: () => new WikiCommandModal(this.app, this, "capture").open() });
    this.addCommand({ id: "xiaoyuanAI-wiki-ingest", name: "\u{1F4E5} Wiki \u6444\u5165", callback: () => new WikiCommandModal(this.app, this, "ingest").open() });
    this.addCommand({ id: "xiaoyuanAI-new-chat", name: "\u{1F4AC} \u65B0\u5EFA AI \u5BF9\u8BDD", callback: () => this.activateChatView() });
    this.addCommand({
      id: "xiaoyuanAI-chat-with-note",
      name: "\u{1F4C4} \u7528\u5F53\u524D\u7B14\u8BB0\u5F00\u542F AI \u5BF9\u8BDD",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u7B14\u8BB0");
          return;
        }
        const content = await this.app.vault.read(file);
        const leaf = this.activateChatView();
        if ((leaf == null ? void 0 : leaf.view) instanceof XiaoyuanAIChatView) {
          leaf.view.addMessage("user", `\u6211\u6709\u4E00\u6BB5\u7B14\u8BB0\u5185\u5BB9\uFF0C\u5E2E\u6211\u5206\u6790\uFF1A

${content.slice(0, 3e3)}`);
        }
      }
    });
    this.addSettingTab(new XiaoyuanAISettingTab(this.app, this));
  }
  activateChatView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_XIAOYUAN_AI_CHAT).first();
    if (!leaf) {
      const useRight = this.settings.chatViewType === "right";
      leaf = useRight ? workspace.getRightLeaf(false) || void 0 : workspace.getLeftLeaf(false) || void 0;
      if (leaf) leaf.setViewState({ type: VIEW_TYPE_XIAOYUAN_AI_CHAT, active: true });
    }
    if (leaf) workspace.revealLeaf(leaf);
    return leaf;
  }
  getActiveEditor() {
    var _a;
    return ((_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor) || null;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async onunload() {
    await stopOpenCodeServer();
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_XIAOYUAN_AI_CHAT);
  }
};
